# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Release01

on:
  push

jobs:
  if: startsWith(github.ref, 'refs/tags/')

  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    permissions:
      contents: write

    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, linux/arm64, windows/386, windows/amd64, darwin/amd64, darwin/arm64
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm64]
        exclude:
          - goarch: "386"
            goos: darwin
          - goarch: arm64
            goos: windows

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Release by wangyoucao577/go-release-action@v1
      uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        binary_name: "github-action-demo"
        extra_files: LICENSE README.md