# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Release01

on:
  push:
    tags:
      - "v*"

jobs:

  build-windows:
    #if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        os: [ubuntu-latest]
      #  goarch: [amd64]
      #  goos: [windows]
        include:
          - goarch: amd64
            goos: linux
            goext: ""
          - goarch: arm64
            goos: windows
            goext: ".exe"

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Get version
      id: get_version
      run: echo "VERSION=$(git tag --points-at HEAD)" >> $GITHUB_OUTPUT
    
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '>=1.19.0'
        cache: true

    - name: Build exe
      run: go build -o demo${{ matrix.goext }}
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
        CGO_ENABLED: 0

    - name: Packaging...
      run: tar czf demo-${{ matrix.goos }}-${{ steps.get_version.outputs.VERSION }}.tgz demo${{ matrix.goext }}

    - name: Uploading artifact
      uses: softprops/action-gh-release@v1
      with:
        files: |
          *.tgz
          README.md